SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS  quality;

SET default_tablespace = '';

CREATE TABLE quality.delivered_products (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    observations character varying(1000),
    status_at timestamp without time zone NOT NULL,
    delivery_id bigint NOT NULL,
    product_id bigint NOT NULL,
    delivery_product_status_id bigint NOT NULL
);

CREATE TABLE quality.delivered_products_attachments (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    observations character varying(1000),
    uuid character varying(36),
    delivered_product_id bigint NOT NULL
);

CREATE TABLE quality.delivered_products_attachments_documents (
    id bigint NOT NULL,
    url character varying(1000) NOT NULL,
    delivered_product_attachment_id bigint NOT NULL
);

ALTER TABLE quality.delivered_products_attachments_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.delivered_products_attachments_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE quality.delivered_products_attachments_ftp (
    id bigint NOT NULL,
    domain character varying(1000) NOT NULL,
    password character varying(60) NOT NULL,
    port character varying(10) NOT NULL,
    username character varying(60) NOT NULL,
    delivered_product_attachment_id bigint NOT NULL
);

ALTER TABLE quality.delivered_products_attachments_ftp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.delivered_products_attachments_ftp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE quality.delivered_products_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.delivered_products_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE quality.delivered_products_attachments_xtf (
    id bigint NOT NULL,
    is_valid boolean,
    report_observations character varying(1000),
    report_revision character varying(1000),
    status character varying(50) NOT NULL,
    url character varying(1000) NOT NULL,
    version character varying(50),
    delivered_product_attachment_id bigint NOT NULL
);

ALTER TABLE quality.delivered_products_attachments_xtf ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.delivered_products_attachments_xtf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE quality.delivered_products_feedbacks (
    id bigint NOT NULL,
    attachment_url character varying(1000),
    created_at timestamp without time zone NOT NULL,
    feedback character varying(1000) NOT NULL,
    delivery_product_id bigint NOT NULL
);

ALTER TABLE quality.delivered_products_feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.delivered_products_feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE quality.delivered_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.delivered_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE quality.deliveries (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    department_name character varying(255) NOT NULL,
    final_comments character varying(1000),
    manager_code bigint NOT NULL,
    manager_name character varying(255) NOT NULL,
    municipality_code character varying(8) NOT NULL,
    municipality_name character varying(255) NOT NULL,
    observations character varying(255) NOT NULL,
    operator_code bigint NOT NULL,
    operator_name character varying(255) NOT NULL,
    status_at timestamp without time zone NOT NULL,
    user_code bigint NOT NULL,
    delivery_status_id bigint NOT NULL
);

ALTER TABLE quality.deliveries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.deliveries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE quality.delivery_product_statuses (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE quality.delivery_product_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.delivery_product_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE quality.delivery_statuses (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE quality.delivery_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.delivery_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE quality.products (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    description character varying(500),
    is_xtf boolean NOT NULL,
    manager_code bigint NOT NULL,
    name character varying(150) NOT NULL
);

ALTER TABLE quality.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME quality.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO quality.delivery_product_statuses VALUES (1, 'PENDIENTE');
INSERT INTO quality.delivery_product_statuses VALUES (2, 'ACEPTADO');
INSERT INTO quality.delivery_product_statuses VALUES (3, 'RECHAZADO');

INSERT INTO quality.delivery_statuses VALUES (1, 'BORRADOR');
INSERT INTO quality.delivery_statuses VALUES (2, 'ENTREGADO');
INSERT INTO quality.delivery_statuses VALUES (3, 'EN REVISIÓN');
INSERT INTO quality.delivery_statuses VALUES (4, 'EN CORRECCIÓN');
INSERT INTO quality.delivery_statuses VALUES (5, 'ACEPTADO');
INSERT INTO quality.delivery_statuses VALUES (6, 'RECHAZADO');

SELECT pg_catalog.setval('quality.delivered_products_attachments_documents_id_seq', 1, false);
SELECT pg_catalog.setval('quality.delivered_products_attachments_ftp_id_seq', 1, false);
SELECT pg_catalog.setval('quality.delivered_products_attachments_id_seq', 1, false);
SELECT pg_catalog.setval('quality.delivered_products_attachments_xtf_id_seq', 1, false);
SELECT pg_catalog.setval('quality.delivered_products_feedbacks_id_seq', 1, false);
SELECT pg_catalog.setval('quality.delivered_products_id_seq', 1, false);
SELECT pg_catalog.setval('quality.deliveries_id_seq', 1, false);
SELECT pg_catalog.setval('quality.delivery_product_statuses_id_seq', 3, true);
SELECT pg_catalog.setval('quality.delivery_statuses_id_seq', 6, true);
SELECT pg_catalog.setval('quality.products_id_seq', 1, false);

ALTER TABLE ONLY quality.delivered_products_attachments_documents
    ADD CONSTRAINT delivered_products_attachments_documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.delivered_products_attachments_ftp
    ADD CONSTRAINT delivered_products_attachments_ftp_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.delivered_products_attachments
    ADD CONSTRAINT delivered_products_attachments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.delivered_products_attachments_xtf
    ADD CONSTRAINT delivered_products_attachments_xtf_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.delivered_products_feedbacks
    ADD CONSTRAINT delivered_products_feedbacks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.delivered_products
    ADD CONSTRAINT delivered_products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.deliveries
    ADD CONSTRAINT deliveries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.delivery_product_statuses
    ADD CONSTRAINT delivery_product_statuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.delivery_statuses
    ADD CONSTRAINT delivery_statuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY quality.deliveries
    ADD CONSTRAINT uk_a4lwgj1e93xxxnogch1s0ic08 UNIQUE (code);

ALTER TABLE ONLY quality.delivered_products_attachments_ftp
    ADD CONSTRAINT fk19e9nhfy9jqpj3jvmtdn6kkc3 FOREIGN KEY (delivered_product_attachment_id) REFERENCES quality.delivered_products_attachments(id);

ALTER TABLE ONLY quality.deliveries
    ADD CONSTRAINT fk3c2ummt8lhcqecq7rqoirvefi FOREIGN KEY (delivery_status_id) REFERENCES quality.delivery_statuses(id);

ALTER TABLE ONLY quality.delivered_products_attachments
    ADD CONSTRAINT fk3jlmglqwow7bd8plv4vbc1iql FOREIGN KEY (delivered_product_id) REFERENCES quality.delivered_products(id);

ALTER TABLE ONLY quality.delivered_products
    ADD CONSTRAINT fkaw7whxefqlx4aqkiid9c9tiqc FOREIGN KEY (product_id) REFERENCES quality.products(id);

ALTER TABLE ONLY quality.delivered_products
    ADD CONSTRAINT fkdsuymk7wwh2km18ritbu5pjg9 FOREIGN KEY (delivery_product_status_id) REFERENCES quality.delivery_product_statuses(id);

ALTER TABLE ONLY quality.delivered_products_attachments_documents
    ADD CONSTRAINT fkgpd3cgamwgeb3cmdwu0k17ct7 FOREIGN KEY (delivered_product_attachment_id) REFERENCES quality.delivered_products_attachments(id);

ALTER TABLE ONLY quality.delivered_products_attachments_xtf
    ADD CONSTRAINT fkictvbaj5e5blwm571xsi1ait8 FOREIGN KEY (delivered_product_attachment_id) REFERENCES quality.delivered_products_attachments(id);

ALTER TABLE ONLY quality.delivered_products_feedbacks
    ADD CONSTRAINT fkk284vmre6ulpni78fwenjvprq FOREIGN KEY (delivery_product_id) REFERENCES quality.delivered_products(id);

ALTER TABLE ONLY quality.delivered_products
    ADD CONSTRAINT fknntxjm95h44o6e02np7lhn9sw FOREIGN KEY (delivery_id) REFERENCES quality.deliveries(id);